### ISSUE TITLE
running ./spf.py  error

### ISSUE THREAD

**Issue by fuckantiviruses** [tatanus/SPF#18]
./spf.py
*** print_tb:
  File "./spf.py", line 13, in <module>
    framework.run(sys.argv[1:])

*** print_exception:
Traceback (most recent call last):
  File "./spf.py", line 13, in <module>
    framework.run(sys.argv[1:])
  File "/root/SPF/spf/core/framework.py", line 994, in run
    self.parse_parameters(argv)
gaierror: [Errno -2] Name or service not known

*** print_exc:
Traceback (most recent call last):
  File "./spf.py", line 13, in <module>
    framework.run(sys.argv[1:])
  File "/root/SPF/spf/core/framework.py", line 994, in run
    self.parse_parameters(argv)
  File "/root/SPF/spf/core/framework.py", line 242, in parse_parameters
    help="IP of webserver defaults to [%s]" % (Utils.getIP()))
  File "/root/SPF/spf/core/utils.py", line 125, in getIP
    ip = socket.gethostbyname(socket.gethostname())
gaierror: [Errno -2] Name or service not known

**Comment by tatanus** [comment]
are you still experiencing this issue?  I have issues a few code changes since this was originally posted.  I just want to see if one of those fixed this issue.

**Comment by TamimDBA** [comment]
Hi I am having the same issue, Can you help?

python3 spf.py --test -d example.com
[!] A CONFIG FILE was not specified...  defaulting to [misc/default.cfg]

1
FIXED = [templates/web/owa]
FIXED = [templates/web/office365]
FIXED = [templates/web/domino]
FIXED = [templates/web/cisco]
FIXED = [templates/web/citrix]
FIXED = [templates/web/juniper_vpn]
FIXED = [templates/web/citrix2]
[*] -------------
[*] TEMPLATE LIST
[*] -------------
[*] ('static', 'templates/web/owa', '')
[*] ('static', 'templates/web/office365', '')
[*] ('static', 'templates/web/domino', '')
[*] ('static', 'templates/web/cisco', '')
[*] ('static', 'templates/web/citrix', '')
[*] ('static', 'templates/web/juniper_vpn', '')
[*] ('static', 'templates/web/citrix2', '')

[*] Starting phishing webserver
[*] [VERBOSE] FIXED = [templates/web/owa]
[*] [VERBOSE] FIXED = [templates/web/office365]
[*] [VERBOSE] FIXED = [templates/web/domino]
[*] [VERBOSE] FIXED = [templates/web/cisco]
[*] [VERBOSE] FIXED = [templates/web/citrix]
[*] [VERBOSE] FIXED = [templates/web/juniper_vpn]
[*] [VERBOSE] FIXED = [templates/web/citrix2]
[*] [VERBOSE] Found the following web sites: [templates/web/owa/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/office365/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/domino/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/cisco/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/citrix/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/juniper_vpn/CONFIG]
[*] [VERBOSE] Found the following web sites: [templates/web/citrix2/CONFIG]
[*] [VERBOSE] Started website [owa       ] on [http://127.0.1.1:8000]
[*] [VERBOSE] Started website [office365 ] on [http://127.0.1.1:8001]
[*] [VERBOSE] Started website [domino    ] on [http://127.0.1.1:8002]
[*] [VERBOSE] Started website [cisco     ] on [http://127.0.1.1:8003]
[*] [VERBOSE] Started website [citrix    ] on [http://127.0.1.1:8004]
[*] [VERBOSE] Started website [junipervpn] on [http://127.0.1.1:8005]
[*] [VERBOSE] Started website [citrix2   ] on [http://127.0.1.1:8006]
[*] [VERBOSE] Started WebServer with pid = [27841]

[*] Obtaining list of email targets
[*] [VERBOSE] Gathering emails via built-in methods
[*] [VERBOSE] Currently searching [google, bing, ask, dogpile, yandex, baidu, yahoo, duckduckgo]
[*] [VERBOSE] [Processing: /] Google
[*] [VERBOSE] [Processing: -] Bing
[*] [VERBOSE] [Processing: |] Ask[!] Could not access [Ask]
[*] [VERBOSE] [Processing: /] Dogpile
[*] [VERBOSE] [Processing: -] Yandex
[*] [VERBOSE] [Processing: /] Baidu
[*] [VERBOSE] [Processing: /] Yahoo
[*] [VERBOSE] [Processing: |] DuckDuckGo
*** print_tb:
  File "spf.py", line 13, in <module>
    framework.run(sys.argv[1:])


*** print_exception:
Traceback (most recent call last):
  File "spf.py", line 13, in <module>
    framework.run(sys.argv[1:])
  File "/home/tamim/SPF/spf/core/framework.py", line 1097, in run
    self.prep_email()
AttributeError: module 'string' has no attribute 'replace'


*** print_exc:
Traceback (most recent call last):
  File "spf.py", line 13, in <module>
    framework.run(sys.argv[1:])
  File "/home/tamim/SPF/spf/core/framework.py", line 1097, in run
    self.prep_email()
  File "/home/tamim/SPF/spf/core/framework.py", line 433, in prep_email
    temp_list = self.gather.emails()
  File "/home/tamim/SPF/spf/core/gather.py", line 23, in emails
    return self.parser.emails()
  File "/home/tamim/SPF/spf/core/parser.py", line 23, in emails
    return Utils.unique_list(reg_emails.findall(Utils.htmlClean(self.text)))
  File "/home/tamim/SPF/spf/core/utils.py", line 90, in htmlClean
    text = string.replace(text, e, ' ')
AttributeError: module 'string' has no attribute 'replace'
tamim@ThinkPad-P52:~/SPF/spf$ Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python3/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tamim/SPF/spf/core/../web.py", line 120, in render_GET
    sys.stdout.flush()
builtins.BrokenPipeError: [Errno 32] Broken pipe

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python3/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tamim/SPF/spf/core/../web.py", line 120, in render_GET
    sys.stdout.flush()
builtins.BrokenPipeError: [Errno 32] Broken pipe

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python3/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tamim/SPF/spf/core/../web.py", line 120, in render_GET
    sys.stdout.flush()
builtins.BrokenPipeError: [Errno 32] Broken pipe

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2013, in lineReceived
    self.allContentReceived()
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 2104, in allContentReceived
    req.requestReceived(command, path, version)
  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 866, in requestReceived
    self.process()
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)
  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)
  File "/usr/lib/python3/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/tamim/SPF/spf/core/../web.py", line 120, in render_GET
    sys.stdout.flush()
builtins.BrokenPipeError: [Errno 32] Broken pipe
![Selection_030](https://user-images.githubusercontent.com/4627165/64919296-abf77e00-d7ca-11e9-8df7-7b189f28f4a1.png)
