### ISSUE TITLE
python web.py default.cfg

### ISSUE THREAD

**Issue by maxriley1** [tatanus/SPF#22]
Cannot load or open the website. Presumably there is something in plain sight that i am missing. Have tried both spf.py --test -d example.com and ./webpy default.cfg

Generating SSL CERT
/bin/bash: certonly: command not found

Traceback (most recent call last):
  File "./web.py", line 323, in <module>
    PhishingWebServer(Utils.load_config(sys.argv[1])).start()
  File "./web.py", line 281, in start
    cert_path = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tatanus** [comment]
There was an issue with the way I was handling SSL certs.  Unfortunately I had to remove the ssl cert support at the moment, but everything else should be working again.
